console.log("Hello from Script");
console.log(document); 
console.log(document.body);
console.log(document.head);
console.log(document.title);
console.log(document.URL);
console.log(document.domain);
console.log(document.doctype);
console.log(document.firstElementChild);
console.log(document.getElementsByTagName("h1"));